[package]
name = "ed25cli"
version = "0.1.0"
authors = ["kajih"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "*"
rand = "*"
ed25519-dalek = "1.0.0-pre.3"

